### PR TITLE
Test against multiple database adapters

### PR DESCRIPTION
**Pull request by richardboehme**
This PR addresses issue #6.

We now run our tests against all major database adapters (SQLite, MySQL and PostgreSQL). Also I added a note on required database collations to the README, which should simplify installation of the gem.

### CODE REVIEW

**Comment by richardboehme** [comment]
Hey guys @fdietz @xanderificnl!

As you were invested in #6, would you mind taking a look over the changes I did here? I hope the information added to the README are fine and understandable enough. Don't worry if you don't have time, I'll just merge it in a few days 😄

**Comment by xanderificnl** [comment]
Good work! 

Perhaps we could consider adding a custom database field for generators, i.e. `rails g migration field:rank` that automatically sets the collation based on the default DB?

**Comment by richardboehme** [comment]
> Good work!

Thanks!

> Perhaps we could consider adding a custom database field for generators, i.e. `rails g migration field:rank` that automatically sets the collation based on the default DB?

I think this would be great! However, as far as I know there is no public API for this in ActiveRecord. If we'd want this, we'd need to add the rank method to the [ColumnMethods](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L254) module and add `rank` to the [valid database types](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L219).

I'm not sure if we really want to do this though. It might add incompatibility between different rails versions or create other problems that I can't see right now. Do you know another gem that does something like this?

Thinking about other approaches I guess we could add a custom generator or a module or something that provides a helper for migrations... However this does not seem too useful to me.

**Comment by fdietz** [comment]
Really like the changes to the README. IMHO this is sufficient.

A custom database field is in my opinion not required, since we don't need any further changes when getting/setting attributes of the rank field.

As example of a gem which uses a custom database field, you can check out [money-rails](https://github.com/RubyMoney/money-rails).

**Comment by xanderificnl** [comment]
Hi,

RE: custom database/migration field. 

The question I was asking myself was: how can we effectively avoid having to set the collation manually? It's a nonstandard thing that can easily be missed/forgotten. 

Even if it's in the readme, I can imagine a year from now using this library in a different app, having written tests (that mock the database) and thinking everything is okay but having forgotten to set the collation.

This is a micro optimalisaties for sure, but it's something we can _probably_ deal with in some way to help ourselves in the future.

I do like the idea of having a rake task that checks the collation and returns feedback.

Anyway I realise these are just random thoughts but this is how I came to think of the custom field :)

**Comment by richardboehme** [comment]
Thanks for both of your feedbacks!

I'm going ahead and merge this for now. I still like the idea of the custom column because it is tightly integrated into the standard rails way. I'll have some more free time in about a month so I will create an issue for this and look into it if I find some more time.

**Pull request merged**
